services:
  api:
    build: .
    container_name: trabalho_final_Back-End
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"